/*
* ========== Copyright Header Begin ==========================================
* 
* OpenSPARC T1 Processor File: 1g2p.conf
* Copyright (c) 2006 Sun Microsystems, Inc.  All Rights Reserved.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES.
* 
* The above named program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License version 2 as published by the Free Software Foundation.
* 
* The above named program is distributed in the hope that it will be 
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
* 
* You should have received a copy of the GNU General Public
* License along with this work; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
* 
* ========== Copyright Header End ============================================
*/
/*
 * Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 *
 * ident	"@(#)1g2p.conf	1.6	06/03/30 SMI"
 */

// 1 guest, 32 processor legion config file

#include "common.hdesc"

system "dumbblue" {
	domain {
		sysclkfreq 0x100000 ;

		processor "niagara" {
			clkfreq 0x400000 ;
			cores 2;
			vthreads 1;
			nglobals 4;
			nwins 8;
			rstv 0xfff0000020;	// Red State Trap Vector value
			maxtl 7;
		}

		addressmap {
			// Hypervisor memory
			device "memory" 1M +63M ;

			// /////////////////////////////////////////////
			// Partition 1
			// /////////////////////////////////////////////

			// memory
			device "memory" 0x80000000 +256M ;

			// disk ... must use virtual_disk directive
			device "memory" 0x1f40000000 +513M  {
				virtual_disk;
				load s0 rom "disk.s10hw2";
			}
			// nvram
			device "memory" 0x1f11000000 +8K {
				shared;
				load +0x0 "nvram1";
			}
			// hypervisor description
			device "memory" 0x1f12080000 +8K {
				rom;
				load +0x0 "1g2p-hv.bin";
			}
			// partition description
			device "memory" 0x1f12000000 +8K {
				rom;
				load +0x0 "1g2p-md.bin";
			}
			// console
			device "dumbserial" PUART0 +0x50 {
				xterm "xterm -l -lf guest1.log -bg black -fg yellow -geometry 80x35+200+30 -T 'Guest Partition #1' -e netcons %s %d &";
			}

			// /////////////////////////////////////////////
			// Misc.
			// /////////////////////////////////////////////

			// OBP ROM
			device "memory" ROMBASE +4M {
				rom;
				load +0x0 "openboot.bin";
			}

			// Boot ROM
			device "memory" RESETADDR +512K {
				rom;
				load +0x0 "reset.bin";
				load +0x10000 "q.bin";
			}


			device "dumbtod" HVTOD +0x8;

			device "dumbserial" HVUART +0x50;
		}
	}
}
